# VelocityGuard Configuration
# This plugin helps prevent extreme speed and flight cheats

# Check settings
checks:
  speed:
    # Maximum horizontal speed in blocks per SECOND
    # Default vanilla walking speed: ~4.3 blocks/s
    # Default vanilla sprinting speed: ~5.6 blocks/s
    # Sprint-jumping can reach speeds of ~9-10 blocks/s temporarily
    # Recommended setting: 10.0 to allow for normal sprint-jumping with a buffer
    max-horizontal-speed: 10.0

# General settings
settings:
  # Enable debug mode for more detailed logging
  # Set to true during development or when troubleshooting issues
  debug-mode: true 