# VelocityGuard Configuration
# This plugin helps prevent extreme speed and flight cheats.

# Configuration for detecting violations.
checks:
  speed:
    # Maximum horizontal speed in blocks per SECOND
    # Default vanilla walking speed: ~4.3 blocks/s
    # Default vanilla sprinting speed: ~5.6 blocks/s
    # Sprint-jumping can reach speeds of ~9-10 blocks/s temporarily
    # Recommended setting: 10.0 to allow for normal sprint-jumping with a buffer
    max-horizontal-speed: 10.0

    # How many seconds to cancel movement when a violation is detected.
    # This will just refuse all movement packets for this duration.
    # Has to be an integer.
    cancel-duration: 3

    # Latency compensation settings
    latency-compensation:
      # Whether to enable latency compensation
      enabled: true
      # Compensation factors for different ping ranges
      # 1.0 means no compensation. Higher values allow more speed
      very-low-ping: 1.1      # 21-50ms ping
      low-ping: 2.1           # 51-100ms ping
      medium-ping: 2.9        # 101-200ms ping
      high-ping: 3.6          # 201-300ms ping
      very-high-ping: 4.6     # 301-500ms ping
      extreme-ping: 5.7       # 501-750ms ping
      ultra-ping: 6.6         # 751-1000ms ping
      insane-ping: 7.5        # 1000+ms ping

    # Burst tolerance settings - number of consecutive violations allowed before punishment
    # Higher ping players get more tolerance due to network inconsistency
    burst-tolerance:
      default: 15             # ≤20ms ping (no compensation)
      very-low-ping: 15       # 21-50ms ping
      low-ping: 20            # 51-100ms ping
      medium-ping: 22         # 101-200ms ping
      high-ping: 24           # 201-300ms ping
      very-high-ping: 27      # 301-500ms ping
      extreme-ping: 30        # 501-750ms ping
      ultra-ping: 33          # 751-1000ms ping
      insane-ping: 35        # 1001+ms ping

    # Knockback adjustment settings
    knockback:
      # Multiplier for speed threshold after taking damage.
      multiplier: 6.0
      # Duration in milliseconds that knockback effect lasts.
      duration: 1000

    # Trident riptide handling.
    riptide:
      # Multiplier for speed threshold after using a trident with riptide enchantment.
      multiplier: 8.0
      # Duration in milliseconds that the riptide effect lasts.
      duration: 3000

    # Elytra movement handling
    elytra:
      # Multiplier for speed threshold while gliding with elytra
      gliding-multiplier: 3.0
      # Duration in milliseconds that landing adjustment lasts after stopping gliding
      landing-duration: 1500

    # Vehicle speed multipliers.
    # Regular vehicle speed multiplier.
    vehicle-speed-multiplier: 1.9

    # Ice vehicle speed multiplier - only applies when vehicles are on ice.
    # Boats on ice can move especially fast.
    vehicle-ice-speed-multiplier: 4.3

    # Extra buffer multiplier applied to all speed checks.
    # This provides some leeway to prevent false positives.
    # Lower values = stricter checks, higher values = more lenient.
    buffer-multiplier: 1.1

# General settings.
settings:
  # Only enable if you are developing or testing the plugin
  # as this results in verbose logging.
  debug-mode: false
