# VelocityGuard Configuration
# This plugin helps prevent extreme speed and flight cheats

# Check settings
checks:
  speed:
    # Maximum horizontal speed in blocks per SECOND
    # Default vanilla walking speed: ~4.3 blocks/s
    # Default vanilla sprinting speed: ~5.6 blocks/s
    # Sprint-jumping can reach speeds of ~9-10 blocks/s temporarily
    # Recommended setting: 10.0 to allow for normal sprint-jumping with a buffer
    max-horizontal-speed: 10.0
    
    # How many seconds to cancel movement when a violation is detected
    # This will just refuse all movement packets for this duration (very effective)
    cancel-duration: 10
  
  chunk-loading:
    # Maximum number of new chunks a player can load per second
    # Lower values will be more strict, but may cause issues with elytra flight
    # Recommended: 8-10 for normal servers
    max-chunks-per-second: 8
    
    # Enable detailed chunk loading metrics
    # This will log when players exceed the chunk loading threshold
    detailed-metrics: false

# General settings
settings:
  # Enable debug mode for more detailed logging
  # Set to true during development or when troubleshooting issues
  debug-mode: true 