name: VelocityGuard
version: '3.4'
main: com.jellypudding.velocityGuard.VelocityGuard
api-version: '26.2'
description: A simple and lightweight plugin to mitigate flight and extreme speed cheats
author: AlphaAlex115
website: www.minecraftoffline.net

commands:
  velocityguard:
    description: Main command for VelocityGuard
    aliases: [vg]
    permission: velocityguard.admin
    usage: "/velocityguard reload"

permissions:
  velocityguard.admin:
    description: Gives access to all VelocityGuard commands
    default: op
