name: VelocityGuard
version: '1.2'
main: com.jellypudding.velocityGuard.VelocityGuard
api-version: '1.21'
description: A simple and lightweight plugin to mitigate extreme speed and flight cheats
author: AlphaAlex115

commands:
  velocityguard:
    description: Main command for VelocityGuard
    aliases: [vg]
    permission: velocityguard.admin
    usage: "/velocityguard reload"

permissions:
  velocityguard.admin:
    description: Gives access to all VelocityGuard commands
    default: op
